[window]
decorations = "full"
opacity = 0.8

  [window.dimensions]
  columns = 100
  lines = 35

[font]
size = 8

  [font.normal]
  family = "JetBrainsMono NF"

  [font.bold]
  family = "JetBrainsMono NF"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono NF"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono NF"
  style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x000b1e"
foreground = "0x0abdc6"

[colors.normal]
black = "0x123e7c"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x123e7c"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.bright]
black = "0x1c61c2"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x00ff00"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.dim]
black = "0x1c61c2"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x123e7c"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"
