{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    #ad-miner # To be backported to 23.11
    aiodnsbrute
    amass
    asn
    assetfinder
    bind
    bloodhound
    bloodhound-py
    cantoolz
    certgraph
    chaos
    checkpwn
    clairvoyance
    cloudlist
    dnsenum
    dnsrecon
    dnstracer
    dnstwist
    dnsx
    dorkscout
    enum4linux
    enum4linux-ng
    fierce
    findomain
    fping
    gau
    geoip
    ghdorker
    #git-hound https://github.com/NixOS/nixpkgs/issues/276787
    gitleaks
    gomapenum
    gowitness
    graphinder
    holehe
    httping
    katana
    kiterunner
    knockpy
    ldeep
    linux-exploit-suggester
    maigret
    maltego
    metabigor
    metasploit
    netdiscover
    netmask
    ntlmrecon
    octosuite
    parsero
    photon
    proxmark3
    python311Packages.shodan
    python311Packages.scrapy
    python311Packages.scrapy-deltafetch
    python311Packages.scrapy-fake-useragent
    python311Packages.scrapy-splash
    python311Packages.spyse-python
    #rita # To be backported to 23.11
    sherlock
    sleuthkit
    smbmap
    sn0int
    sniffglue
    snmpcheck
    snscrape
    social-engineer-toolkit
    socialscan
    subfinder
    subjs
    thc-ipv6
    theharvester
    traceroute
    trufflehog
    uncover
    webanalyze
    websploit
    whatweb
    zgrab2
  ];
}
