name: "🐞Bug report"
description: Report a bug
title: "[BUG]: "
labels: ["bug", "triage"]
body:
- type: markdown
  attributes:
    value: |
      Please [search for existing issues](https://github.com/Athena-OS/athena-iso/issues) before creating a new one.

- type: input
  attributes:
    label: Athena OS version
    description: |
      Please run `cat /etc/dev-rel | grep "ISO_RELEASE" | awk -F"=" '{print $2}'` to get the build of Athena OS you are on.
      You can get additional information about the version where possible, e.g. run `lsb_release -a`
    placeholder: "Athena OS v[xx.yy.zz]"
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Which environment or technology are you using?
    description: |
      Tell us which environment the issue is affecting. 
    options:
      - label: "Baremetal"
      - label: "VirtualBox Virtual Machine"
      - label: "VMware Virtual Machine"
      - label: "Hyper-V Virtual Machine"
      - label: "QEMU/KVM"
      - label: "Parallels"
      - label: "UTM"
      - label: "Container"
      - label: "WSL"

- type: input
  attributes:
    label: Kernel version
    description: |
      Please tell us what version of the Linux kernel you are using, or if you are using a custom kernel. 
      You can run `uname -r` if that command is available to you, or by running `cat /proc/version`.
    placeholder: "6.2.11-lts1-1-lts"
  validations:
    required: false

- type: textarea
  attributes:
    label: Involved software
    description: If you're reporting a bug involving Athena OS interaction with other applications, please tell us. What applications? What versions?
    placeholder: |
      docker, version 3.2.2
      traceroute, Version: 1:2.0.21-1
      codium 1.54.3 with Remote-WSL Extension 0.54.6
      MyCustomApplication
  validations:
    required: false

- type: textarea
  attributes:
    label: Repro steps
    description: Please list out the steps to reproduce your bug.  
    placeholder: Your steps go here. Include relevant environmental variables or any other configuration.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: What were you expecting to see? Include any relevant examples or documentation links.
    placeholder: If you want to include screenshots, paste them into the text area or follow up with a separate comment. 
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual behavior
    description: What happened instead?
    placeholder: Include the terminal output, straces of the failing command, etc. as necessary.
  validations:
    required: true

- type: textarea
  attributes:
    label: Diagnostic logs
    description: | 
      Please provide additional diagnostics if needed.
      You can run `probe` and `sudo journalctl | tb` to generate link with logs accessible online.
    placeholder: Your links to logs or other information go here.
  validations:
    required: false
