post_install() {
  echo "Setting Aether as your default login theme"

  sed -i 's/^webkit_theme\s*=\s*\(.*\)/webkit_theme = lightdm-webkit-theme-aether/g' /etc/lightdm/lightdm-webkit2-greeter.conf
  sed -i 's/^\(#\?greeter\)-session\s*=\s*\(.*\)/greeter-session=lightdm-webkit2-greeter/g' /etc/lightdm/lightdm.conf
  rm -rf /usr/share/plymouth/themes/spinner/watermark.png
  mv /usr/share/lightdm-webkit/themes/lightdm-webkit-theme-aether/watermark-athena.png /usr/share/plymouth/themes/spinner/watermark.png
}

post_upgrade() {
    post_install $1
}
