#!/bin/sh
#thank you Garuda team
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Restart" --class restart {
	echo "System rebooting..."
	reboot
}

menuentry "Shutdown" --class shutdown {
	echo "System shutting down..."
	halt
}


