#!/bin/sh

detect_virt=$(systemd-detect-virt)

if ([ ! -z "$DISPLAY" ] && [ "$DISPLAY" != ":0" ]) || ([ "$detect_virt" != "docker" ] && [ "$detect_virt" != "podman" ] && [ "$detect_virt" != "wsl" ]); then

     FLAGFILE="$HOME/.flag-mate-once"
     #FLAGNET="$HOME/.flag-mate-net-once"

     DCONF_PN="/usr/share/mate/dconf-panel.ini"

     if [ -f "$FLAGFILE" ]; then

         cat $DCONF_PN | dconf load /org/mate/panel/

         sh ~/.vim_runtime/install_awesome_parameterized.sh ~/.vim_runtime $USER

         theme-switcher -a

         rm -rf "$FLAGFILE"

         systemctl --user enable --now psd
     fi

     #if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
     #    if [ -f "$FLAGNET" ]; then
     #    # Commented for keeping nist-feed disable. The user decides if enable it.
     #    #	/usr/local/bin/nist-feed -n -l
     #    	rm -rf "$FLAGNET"
     #    fi
     #    /usr/local/bin/htb-update
     #fi

     #If tun0 is down (i.e., after a reboot), the shell prompt must be updated with the running interfaces
     #if ! nmcli c show --active | grep -q tun ; then

     #   /usr/local/bin/prompt-reset

     #fi
fi
