name: Build ArchISO Beta
on:
  # push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */7 * *'
  
jobs:
  build:
    env:
      ATHENA_VERSION: 'unstable'
      ISO_VERSION: '2023.06.01' # It must be the same on profiledef.sh and installation_script
      ISO_ARCHITECTURE: 'x86_64'
    runs-on: ubuntu-22.04
    container:
      image: athenaos/base-devel:latest
      options: --privileged 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pacman -Syyu --noconfirm archiso git openssh rsync sshpass wget
          
      - name: Retrieve Athena ISO
        run: git clone https://github.com/Athena-OS/athena-iso
        
      - name: Build ArchISO
        run: |
          sed -i 's/install -m 0644 -- "\${files_to_copy\[@\]}"/cp -r -- "\${files_to_copy\[@\]}"/g' /usr/bin/mkarchiso
          mkdir -p $HOME/Athena-Out
          touch athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso
#          cd athena-iso/installation-scripts
#          ./30-build-the-iso-the-first-time.sh
          
      - name: Deploy to Dropbox
        uses: aTable/deploy-to-dropbox@v1.0.7
        with:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DROPBOX_DESTINATION_PATH_PREFIX: "/"
          GLOB: "$HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso"
          DEBUG: false
          
#      - name: Upload to SourceForge
#        run: |
#          sshpass -p "${{ secrets.SOURCEFORGE_TOKEN }}" rsync -avP -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso ${{ secrets.SOURCEFORGE_USER }}@frs.sourceforge.net:/home/frs/project/athena-iso/${{env.ATHENA_VERSION}}
