name: Build ArchISO Beta
on:
  # push:
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 0 */7 * *'
  
jobs:
  build:
    env:
      ATHENA_VERSION: 'unstable'
      ISO_VERSION: 'test' # It must be the same on profiledef.sh and installation_script
      ISO_ARCHITECTURE: 'x86_64'
    runs-on: ubuntu-22.04
    container:
      image: athenaos/base-devel:latest
      options: --privileged 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
          
      - name: Install dependencies
        run: pacman -Syyu --noconfirm archiso git openssh rsync sshpass wget
          
      - name: Retrieve Athena ISO
        run: git clone https://github.com/Athena-OS/athena-iso
        
      - name: Build ArchISO
        run: |
          sed -i 's/install -m 0644 -- "\${files_to_copy\[@\]}"/cp -r -- "\${files_to_copy\[@\]}"/g' /usr/bin/mkarchiso
          cd athena-iso/installation-scripts
          ./30-build-the-iso-the-first-time.sh
#          mkdir -p $HOME/Athena-Out
#          touch $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso
#          echo "ciao" > $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso
          
#      - name: Deploy to Dropbox
#        uses: whalemare/action-dropbox@v1.0.0
#        with:
#          accessToken: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
#          destination: "/"
#          file: "$HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso"
          
      - name: Upload to SourceForge
        run: |
          sshpass -p "${{ secrets.SOURCEFORGE_TOKEN }}" rsync -avP -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso.md5 $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso.sha1 $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso.sha256 $HOME/Athena-Out/athena-${{env.ISO_VERSION}}-${{env.ISO_ARCHITECTURE}}.iso.sha512 ${{ secrets.SOURCEFORGE_USER }}@frs.sourceforge.net:/home/frs/project/athena-iso/${{env.ATHENA_VERSION}}
