name: Upload Athena Nix to Hub
on:
  # push:
  workflow_dispatch:
  # schedule:
  #    - cron:  '0 0 */7 * *'
  
jobs:
  build:
    env:
      ATHENA_VERSION: 'rolling'
      ISO_VERSION: 'rolling' # It must be the same on profiledef.sh and installation_script
      ISO_ARCHITECTURE: 'x86_64'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        
      - name: Get Athena-Nix
        run: |
          curl -o athena-nix.zip https://codeload.github.com/Athena-OS/athena-nix/zip/refs/heads/main

      - name: Upload to Athena OS Hub
        run: |
          sshpass -p "${{ secrets.MIRROR_SECRET }}" rsync -avzzlr --delete -e "ssh -p 1027 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" athena-nix.zip ${{ secrets.MIRROR_USER }}@hub.athenaos.org:/srv/mirrors/athena-nix/23.11/