name: Test

on:
   workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest
      options: --privileged

    steps:
      - name: Create a raw disk image
        run: |
             dd if=/dev/zero of=disk.img bs=1M count=15360  # Create a 15GB disk image
             if losetup -a | grep -q "/dev/loop0"; then
                 losetup -d /dev/loop0
             fi
             ls -la /dev/
             losetup -a
             lsblk
             fdisk -l
             mount | grep "/dev/loop"
             lsof /dev/loop0
             umount /dev
