name: Test

on:
   workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest
      options: --privileged

    steps:
      - name: Create a raw disk image
        run: |
             systemd-detect-virt
