name: Test Installation
on:
  # push:
  workflow_dispatch:
  schedule:
     - cron:  '0 0 */7 * *'
  
jobs:
  Quicktest:
    env:
      RELEASE_VERSION: 'v23.11'
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest
      options: --privileged 
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install Quicktest
        run: | 
          pacman -Syyu quickemu qemu-desktop socat ffmpeg imagemagick tesseract tesseract-data-eng
          git clone https://github.com/quickemu-project/quicktest

      - name: Run Test
        run: |
          cd quicktest
          mkdir -p testcases/athenaos/${{env.RELEASE_VERSION}}
          curl -o testcases/athenaos/${{env.RELEASE_VERSION}}/test_install_entire_disk_with_defaults https://raw.githubusercontent.com/Athena-OS/athena/main/tests/test_install_entire_disk_with_defaults
          QUICKEMU_WIDTH=1024 QUICKEMU_HEIGHT=768 ./quicktest test_install_entire_disk_with_defaults athenaos ${{env.RELEASE_VERSION}}
